name: Test Workflow

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  # Also run on push to any branch
  push:
    branches: [ '*' ]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Hello World
        run: echo "Hello World! This is a test workflow to verify GitHub Actions is working."
        
      - name: Show Repository Info
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
          echo "Commit: ${{ github.sha }}"
          
      - name: Current Date
        run: date
